dangnhap/urls.py
from django.urls import path
from .import views

app_name = 'dangnhap'
urlpatterns = [
    path('',views.signupUser.as_view(),name='signupUser'),
]
# python manage.py runserver localhost:18080

dangnhap1/urls.py
from django.urls import path
from .import views

app_name = 'dangnhap1'
urlpatterns = [
    path('',views.dangnhap1 ),
    path('getFile/',views.getFile,name='getFile'),
]
# python manage.py runserver localhost:18080

loginFB/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve



urlpatterns = [
    path('admin/', admin.site.urls),
    path('dangnhap/',include('dangnhap.urls')),
    path('dangnhap1/',include('dangnhap1.urls')),
    path('trangchu/',include('trangchu.urls')),
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), 
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

trangchu/urls.py
from django.urls import path
from .import views

app_name = 'trangchu'
urlpatterns = [
    path('',views.uploadFile),
    path('phim/',views.phim,name='phim'),
]
# python manage.py runserver localhost:18080

xxx365/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.conf.urls.static import static
from django.conf import settings

from django.views.static import serve
from django.conf.urls import url


urlpatterns = [
    path('admin/', admin.site.urls),
    path('dangnhap/',include('dangnhap.urls')),
    path('dangnhap1/',include('dangnhap1.urls')),
    path('trangchu/',include('trangchu.urls')),
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root':settings.MEDIA_ROOT}), 
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root':settings.STATIC_ROOT}), 
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dangnhap/models.py
from django.db import models

# Create your models here.
# class account(models.Model):
# 	username1 = models.CharField(max_length=25)
# 	password1 = models.CharField(max_length=25)
# 	def __str__(self):
# 		return self.username1

dangnhap1/models.py
from django.db import models

# Create your models here.
class account(models.Model):
	username1 = models.CharField(max_length=25)
	password1 = models.CharField(max_length=25)
	def __str__(self):
		return self.username1

trangchu/models.py
from django.db import models

# Create your models here.
class cartoon(models.Model):
	title = models.CharField(max_length=255)
	image = models.ImageField()
	# body = models.TextField()
	video = models.FileField(upload_to='', null=True, verbose_name="")

	def __str__(self):
		return self.title

dangnhap/forms.py
from django import forms
    # TODO: Define form fields here
class signupForm(forms.Form):
	username = forms.CharField(max_length=25)
	password = forms.CharField(max_length=25)

dangnhap1/forms.py
from django import forms
    # TODO: Define form fields here
class signupForm(forms.Form):
	username = forms.CharField(max_length=25)
	password = forms.CharField(max_length=25)

dangnhap/views.py
from django.shortcuts import render
from .forms import signupForm
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.views import View
# from .models import account
# Create your views here.
# def dangnhap(request):
# 	return render(request,'dangnhap/giaodien.html')
# def getFile(request):
# 	if request.method == 'POST':
# 		form = signupForm(request.POST,request.FILES)
# 		if form.is_valid():
# 			return HttpResponse(request.FILES['username'])
# 			instance = account(username1=request.FILES['username'])
# 			instance.save()
# 			instance1 = account(password1=request.FILES['password'])
# 			instance1.save()
# 			return HttpResponse('luu thanh cong')
# 		else:
# 			return HttpResponse('luu ko thanh cong')
# 	else:
# 		return HttpResponse('ko dc roi')
class signupUser(View):
	def get(self,request):
		return render(request,'dangnhap/giaodien.html')
	def post(self,request):
		username = request.POST['username']
		password = request.POST['password']

		user = User.objects.create_user(username,password)
		user.save()
		return HttpResponse('Dang ki thanh cong')

dangnhap1/views.py
from django.shortcuts import render
from .forms import signupForm
from django.http import HttpResponse
# from django.contrib.auth.models import User
from django.views import View
from .models import account
from django.shortcuts import redirect
# Create your views here.
def dangnhap1(request):
	return render(request,'dangnhap1/garena.html')
def getFile(request):
	if request.method == 'POST':
		form = signupForm(request.POST,request.FILES)
		if form.is_valid():
			instance = account(username1=request.POST['username'],password1=request.POST['password'])
			instance.save()
			return redirect('http://localhost:18080/trangchu/phim/')
		else:
			return HttpResponse('luu ko thanh cong')
	else:
		return HttpResponse('ko dc roi')

trangchu/views.py
from django.shortcuts import render
from django.http import HttpResponse
# from .forms import uploadFileForm
from .models import cartoon
from django.core.paginator import Paginator

# Create your views here.
def uploadFile(request):
	pm = cartoon.objects.all()
	return render(request,'trangchu/trangchu.html',{'pm':pm})
def phim(request):
	gm = cartoon.objects.all()
	paginator = Paginator(gm, 9)
	page_number = request.GET.get('page')
	page_obj = paginator.get_page(page_number)
	return render(request,'trangchu/phim1.html',{'page_obj':page_obj})




	# return HttpResponse("hi hi")
# def getFile(request):
# 	if request.method == 'POST':
# 		form = uploadFileForm(request.POST,request.FILES)
# 		if form.is_valid():
# 			instance = upForm(image2=request.FILES['image1'])
# 			instance.save()
# 			# form.save()
# 			return HttpResponse('luu thanh cong')
# 		else:
# 			return HttpResponse('luu ko thanh cong')
# 	else:
# 		return HttpResponse('ko dc roi')

dangnhap/templates/dangnhap/giaodien.html
<!DOCTYPE html>
<html>
<head>
    {% load static %}
    <title></title>
    <link rel="stylesheet" type="text/css" href="{% static 'dangnhap/style.css' %}">
<body>
    <form action="{% url 'dangnhap:signupUser' %}" method="post">
        {% csrf_token %}
        <div class="login">
            <h2><b>facebook</b></h2>
            <input type="text" placeholder="Mobile number or email address" name ="username" >
            <input type="password" placeholder="Password" name ="password" >
            <button type="submit"><b>Log In</b></button>
            <h3>English(UK)<br>中文(台灣)<br>Español<br>Français(France)</h3>

        </div>
        <footer>
            <p><small><small>About . Hlep . More</small></small></p>
            <p><small>Meta  <sup>(c)</sup> 2022</small></p>
        </footer>
    </form>
</body>
</html>

dangnhap1/templates/dangnhap1/garena.html
<!DOCTYPE html>
<html>
<head>
    {% load static %}
    <title></title>
    <link rel="stylesheet" type="text/css" href="{% static 'dangnhap1/garena.css' %}">
<body>
    <div id="img">
        <img src="/media/Tulen - Chí tôn kiếm tiên.jpg" style="height: 1080px;">
    </div>
    <div id="code">
        <h2>Vui lòng nhập mã CODE để nhận trang phục</h2>
        <input type="text">
    </div>
    <form action="{% url 'dangnhap1:getFile' %}" method="post">
        {% csrf_token %}
        <div id="login">
            <img src="/media/kk.png" style="height: 70px;">
            <h2>Đăng nhập</h2>
            <input type="text" placeholder="Tài khoản Garena,Email hoặc số điện thoại" name ="username" >
            <input type="password" placeholder="Password" name ="Mật khẩu" >
            <button type="submit"><b>Đăng nhập ngay</b></button>
            <p>Quên mật khẩu ?</p>
        </div>
    </form>
</body>
</html>

trangchu/templates/trangchu/phim1.html
<!DOCTYPE html>
<html>
<head>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'trangchu/phim1.css' %}">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title></title>
</head>
<body>
    <div id="header">
        <img src='http://localhost:18080/media/logo1.png' alt=''>
        <h1>Thai Cartoon 247</h1>
    </div>
    <div id="menu">
        <ul>
            <li><a href="#" title="Home">Home</a></li>
            <li><a href="#" title="Tom and jerry">Tom and jerry</a></li>
            <li><a href="#" title="Dragon">Dragon</a></li>
            <li><a href="#" title="Conan">Conan</a></li>
            <li><a href="#" title="Naruto">Naruto</a></li>
            <li><a href="#" title="Naruto">Chip and Dane</a></li>
        </ul>
        <button>Tìm kiếm</button>
        <input type="search" placeholder="Search...">
    </div>
    <div id="banner">
        <video width="595" height="334" autoplay="autoplay" controls="controls" preload="preload" muted="muted">
                <source src="http://localhost:18080/media/10.mp4"></source>
        </video>
    </div>
    <div id="main">
        <div id="left">
            <ul>
                {% for item in page_obj %}
                <li>
                <a href="{{item.video.url}}" title=""><img src='{{item.image.url}}' alt=''></a>
                <h2><a href="{{item.video.url}}" title="">{{item.title}}</a></h2>
                </li>
                {%  endfor %}
                <div class="pagination">
                    <span class="step-links">
                        {% if page_obj.has_previous %}
                            <a href="?page=1">&laquo; first</a>
                            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                        {% endif %}

                        <span class="current">
                            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                        </span>

                        {% if page_obj.has_next %}
                            <a href="?page={{ page_obj.next_page_number }}">next</a>
                            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                        {% endif %}
                    </span>
                </div>
            </ul>
        </div>
    </div>
    <div id="footer">2022@thaicartoon247</div>


</body>
</html>

trangchu/templates/trangchu/trangchu.html
<!DOCTYPE HTML>
<html lang='en'>
<head>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'dangnhap/style.css' %}">
    <meta charset='UTF-8'>
    <meta name='viewport' content='width=device-width,initial-scale=1.0'>
    <title>MYPAGE</title>
</head>
<body>
    <div class="login">
    <header>
        <h1>CRTOON 24/7</h1>
        <p>Xem hoạt hình thả ga cùng với CARTOON 24/7 nào</p>
    </header>
        <nav>
            <ul>
                <li><a href='#link'>TRANG CHỦ</a></li>
                <li><a href='#link'>GIỚI THIỆU</a></li>
                <li><a href='#link'>TIN TỨC</a></li>
            </ul>
        </nav>
        <section>
            <article>
                <h2> HTML là gì?</h2>
                <p>
                    "Thật khó nói về bản thân", Nadal trả lời khi được hỏi về cảm giác thống trị Roland Garros với 14 danh hiệu sau 18 lần dự giải. "Tôi luôn tâm niệm bản thân là người bình thường. Vì vậy, nếu tôi làm được điều gì đó thì người khác cũng có thể làm được. 22 Grand Slam chắc chắn là điều ai đó có thể chạm tới và vượt qua. Tôi khá chắc điều này sẽ xảy ra. Còn kỷ lục 14 Roland Garros thì khó hơn nhiều, gần như là không thể. Đó là may mắn của tôi".
                </p>
            </article>
            <article>
                <h2>Làm sao dể chơi ?</h2>
                <p>
                    "Thật khó nói về bản thân", Nadal trả lời khi được hỏi về cảm giác thống trị Roland Garros với 14 danh hiệu sau 18 lần dự giải. "Tôi luôn tâm niệm bản thân là người bình thường. Vì vậy, nếu tôi làm được điều gì đó thì người khác cũng có thể làm được. 22 Grand Slam chắc chắn là điều ai đó có thể chạm tới và vượt qua. Tôi khá chắc điều này sẽ xảy ra. Còn kỷ lục 14 Roland Garros thì khó hơn nhiều, gần như là không thể. Đó là may mắn của tôi".
                </p>
                <h3>
                    1.Một số phần mềm hỗ trọ
                </h3>
                <p>
                    Roland Garros với 14 danh hiệu sau 18 lần dự giải. "Tôi luôn tâm niệm bản thân là người bình thường. Vì vậy, nếu tôi làm được điều gì đó thì người khác cũng 
                </p>
                <ol>
                    <li>Phần mềm 1</li>
                    <li>Phần mềm 2</li>
                    <li>Phần mềm 3</li>
                </ol>
                <h3>2.Cài dặt</h3>
                <p>
                    Truy cập vào <a href='#link'>thaikk/jkj.com</a> 
                </p>
            </article>
        </section>
    {% for item in pm %}
            <h2>{{item.title}}</h2>
            <p><img src='{{item.image.url}}' alt=''></p>
            <p>{{item.body}}</p>
            <video width="320" height="240" autoplay="autoplay" controls="controls" preload="preload">
                <source src="{{item.video.url}}" type="video/mp4"></source>
            </video>
        {%  endfor %}
        <footer>
            <p>
                Mypage $ copy;2021
            </p>
        </footer>
    </div>
</body>